#Q.1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?



**Purpose of NumPy:**

**1. Efficient Array Handling:** At its core, NumPy provides a powerful N-dimensional array object called ndarray. This array allows efficient storage and manipulation of large datasets, making it ideal for scientific computing tasks.

**2. Mathematical Operations:** NumPy includes functions for performing a wide range of mathematical operations on arrays, such as linear algebra, random number generation, Fourier transforms, and statistics.

**3. Interfacing with Other Libraries:** It forms the foundation for many other scientific libraries, such as SciPy, pandas, and Matplotlib. It also facilitates easy integration with other languages like C and Fortran for performance-critical operations.

**Advantages of NumPy in Scientific Computing and Data Analysis:**

**1. Performance and Speed:** NumPy is implemented in C, which makes array operations much faster than using Python’s built-in list types. This is especially important for large datasets or complex calculations, where Python's default performance can be a bottleneck.

**2. Memory Efficiency:** NumPy arrays use much less memory compared to Python lists. This is because NumPy stores data in contiguous memory blocks, and arrays are of fixed data types, meaning it doesn’t need to store additional metadata for each element, as lists do.

**3. Vectorized Operations:** One of the biggest advantages of NumPy is its ability to perform vectorized operations. Instead of writing loops, you can perform operations on entire arrays at once, which not only makes the code cleaner but also much faster.

**4. Mathematical Functions and Tools:** NumPy includes a comprehensive set of mathematical functions that operate on arrays in an optimized manner, making it easy to perform complex numerical operations such as matrix multiplication, statistical operations, and solving linear equations.

**5. Support for Multi-Dimensional Data:** It is highly efficient for working with multi-dimensional data, which is a common requirement in fields like data science, physics, and engineering. You can easily create and manipulate arrays of any dimension using NumPy.

**6. Broadcasting:** NumPy’s broadcasting allows arithmetic operations between arrays of different shapes and sizes without needing to explicitly reshape them. This leads to simpler and more intuitive code.

**7. Cross-Library Compatibility:** Many other Python libraries for scientific computing and data analysis (like pandas, TensorFlow, or PyTorch) are built on top of NumPy arrays, which makes NumPy a critical building block in the Python scientific computing ecosystem.


In [2]:
import numpy as np
# Without NumPy (looping over lists):
result = [i**2 for i in range(1000)]

# With NumPy:
arr = np.arange(1000)
result = arr**2

# Q. 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Both np.mean() and np.average() are used to calculate the average of an array in NumPy, but they have some key differences in functionality and use cases. Here’s a comparison of the two:

**1. np.mean()**

**Purpose:** np.mean() calculates the arithmetic mean (average) of elements along a given axis or for the entire array if no axis is specified.

**Syntax**
 np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

**Weights:** It does not support weighting of elements; every element contributes equally to the mean.

**Return Type:** Returns the mean of the array elements. If the array is multi-dimensional, the result can be reduced along a specified axis.

**Use Case:** Use np.mean() when you need to calculate a simple arithmetic mean without considering any weights.

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4])
mean_value = np.mean(arr)
print(mean_value)  # Output: 2.5

2.5


**2. np.average()**

**Purpose:** np.average() computes the weighted average of elements in the array. If no weights are provided, it defaults to a simple arithmetic mean, similar to np.mean().

**Syntax**
 np.average(a, axis=None, weights=None, returned=False)

**Weights:** Supports an optional weights parameter, allowing you to compute a weighted average. If weights is provided, each element is multiplied by its corresponding weight before calculating the average.

**Return Type:** Returns the weighted average. If returned=True, it returns a tuple of the weighted average and the sum of the weights.

**Use Case:** Use np.average() when you need to compute a weighted average, i.e., when different elements in the array should contribute to the average with different weights.

In [4]:
arr = np.array([1, 2, 3, 4])
weights = np.array([0.1, 0.2, 0.4, 0.3])
weighted_avg = np.average(arr, weights=weights)
print(weighted_avg)  # Output: 2.9

2.9000000000000004


# Q. 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for ID and 2D arrays.

Reversing a NumPy array means flipping its elements along a specific axis. There are several ways to reverse a NumPy array, depending on whether it's a 1D, 2D, or multi-dimensional array. Here's a breakdown of the methods:

**1. Reversing a 1D Array**

For a 1D array (a simple list of elements), you can reverse the elements using slicing or the np.flip() function.

Method 1: Using Slicing ([::-1])
This method reverses the order of elements in the array.

Example:

In [5]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]

print(reversed_arr_1d)
# Output: [5 4 3 2 1]

[5 4 3 2 1]


Method 2: Using np.flip()
The np.flip() function reverses the elements along a specified axis. For a 1D array, it will reverse the entire array.

**Example:**

In [6]:
reversed_arr_1d = np.flip(arr_1d)

print(reversed_arr_1d)
# Output: [5 4 3 2 1]

[5 4 3 2 1]


2. Reversing a 2D Array
For a 2D array (matrix), you can reverse the elements along different axes (rows or columns) or both.

**Method 1:** Using Slicing
Reverse Rows: Reverse the order of the rows (axis 0).

**Example:**

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]

print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]


Reverse Columns: Reverse the order of the columns (axis 1).

**Example:**

In [8]:
reversed_columns = arr_2d[:, ::-1]

print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]


Reverse Both Rows and Columns: Reverse the array entirely by reversing both axes.

**Example:**

In [9]:
reversed_both = arr_2d[::-1, ::-1]

print(reversed_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]


#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

To determine the data type of elements in a NumPy array, you use the .dtype attribute. This attribute returns an object that describes the data type of the array’s elements. Here’s how you can use it:

Checking Data Type with .dtype

**Example:**

In [10]:
import numpy as np

arr_int = np.array([1, 2, 3, 4, 5])
arr_float = np.array([1.0, 2.0, 3.0])

print(arr_int.dtype)   # Output: int64 (or int32 depending on platform)
print(arr_float.dtype) # Output: float64

int64
float64


In this example:

arr_int.dtype returns int64 (or int32, depending on the system), indicating that the array elements are 64-bit integers.
arr_float.dtype returns float64, indicating that the elements are 64-bit floating-point numbers.
Importance of Data Types in Memory Management and Performance
Memory Efficiency:

**Storage Requirements:** Different data types consume different amounts of memory. For example, an int32 takes up 4 bytes, while an int64 takes up 8 bytes. Using an appropriate data type can help minimize memory usage. If you don’t need the precision of float64, using float32 can save memory.

**Array Size:** Larger data types can increase the overall size of the array, which may lead to higher memory consumption and potential performance issues.

**Performance:**

**Speed of Operations:** Operations on arrays with smaller data types can be faster because they involve less data to process. For example, integer operations on int32 arrays can be faster than on int64 arrays.

**Vectorization:** NumPy leverages low-level optimizations and vectorized operations that are influenced by the data type. Choosing the right data type ensures that these optimizations are fully utilized.

**Compatibility:**

**Interfacing with Other Libraries:** Many scientific libraries (e.g., SciPy, TensorFlow) and file formats expect specific data types. Using the correct data type ensures compatibility and proper functioning when interfacing with other tools or saving data to files.
Precision:

**Numerical Precision:** The choice between different floating-point types (float32 vs. float64) affects the precision of calculations. Using float64 allows for more precision but requires more memory and computational resources. For tasks requiring high precision, float64 is preferred.
Avoiding Errors:

**Type Casting Issues:** Using the wrong data type might lead to unintended type casting or loss of information. For example, storing a very large integer in an int8 array will result in overflow and incorrect values.

#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, ndarray stands for "n-dimensional array" and is the core data structure provided by the library. It is a powerful object for numerical computations, providing efficient storage and manipulation of large datasets. Here’s a detailed overview of ndarray and how it differs from standard Python lists:

**Key Features of ndarray:**

**1. N-Dimensional Array:**

ndarray can handle arrays with any number of dimensions (1D, 2D, 3D, etc.). This flexibility allows for the representation of vectors, matrices, and higher-dimensional data structures.

Example: A 2D ndarray can represent a matrix, while a 3D ndarray might represent a stack of matrices or a voxel grid.

**2. Homogeneous Data Types:**

All elements in a NumPy array are of the same data type. This uniformity allows for efficient computation and memory management.

**Example:8** An ndarray of type float64 will store all elements as 64-bit floating-point numbers.

**3. Contiguous Memory Storage:**

ndarray objects are stored in contiguous blocks of memory. This storage structure enables fast access and efficient operations on large datasets.
Example: Accessing elements in a NumPy array is generally faster than accessing elements in a Python list because of the way data is stored in memory.

**4. Element-wise Operations:**

NumPy supports element-wise operations, which means that you can perform arithmetic operations, comparisons, and other functions on entire arrays without the need for explicit loops.

**Example:** You can add, subtract, multiply, or divide arrays directly.

**5. Broadcasting:**

Broadcasting is a powerful feature that allows NumPy to perform operations on arrays of different shapes. It automatically handles shape mismatches in a way that makes operations efficient and intuitive.

**Example:** Adding a scalar to an array adds the scalar to each element of the array.

**6. Vectorization:**

NumPy operations are vectorized, which means they are implemented using low-level optimized code (often written in C) that avoids Python’s loop overhead. This results in faster computations.
Example: Vectorized functions like np.sum() compute sums much faster than a Python loop doing the same task.

**7. Advanced Indexing and Slicing:**

NumPy arrays support advanced indexing and slicing, allowing for more complex data extraction and manipulation compared to standard Python lists.

**Example:** You can use boolean masks or integer arrays to index elements.

**8. Mathematical Functions:**

NumPy provides a wide array of mathematical functions that operate on arrays, such as linear algebra operations, statistical functions, and Fourier transforms.

**Example:** Functions like np.mean(), np.dot(), and np.fft.fft() are available for various mathematical operations.

**Differences from Standard Python Lists:**

**1. Performance:**

**NumPy:** Arrays are implemented in C and optimized for performance, especially for large datasets and mathematical operations. Operations on NumPy arrays are faster and more efficient.

**Python Lists:** Lists are slower for numerical operations because they are not optimized for such tasks and involve overhead for dynamic typing and storage.

**2. Data Type:**

**NumPy:** Arrays require all elements to be of the same data type, which enables more efficient memory usage and faster computation.

**Python Lists:** Lists can contain elements of different types, which can lead to increased overhead and slower performance.

**3. Memory Efficiency:**

**NumPy:** Arrays use less memory due to their fixed data type and contiguous memory storage. This allows handling larger datasets with less memory consumption.

**Python Lists:** Lists use more memory because they store additional information about the type of each element and can have more overhead due to dynamic resizing.

**4. Operations and Functionality:**

**NumPy:** Provides a rich set of functions and operations for numerical computing, including element-wise operations, broadcasting, and advanced indexing.

**Python Lists:** Support basic operations and methods like appending and slicing but lack specialized functions for numerical tasks.

**5. Dimensionality:**

**NumPy:** Supports multi-dimensional arrays, allowing complex data structures like matrices and tensors to be easily handled.

**Python Lists:** Primarily one-dimensional; multi-dimensional data structures are usually represented as lists of lists, which can be less efficient and more cumbersome to work with.

#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations. Here’s a detailed analysis of these benefits:

**Performance Benefits of NumPy Arrays**

**1. Contiguous Memory Allocation:**

**NumPy:** Arrays are stored in contiguous blocks of memory, which allows for efficient access and manipulation of data. This layout minimizes cache misses and maximizes the speed of memory operations.

**Python Lists:** Lists are arrays of pointers to objects, leading to non-contiguous memory allocation. This can result in slower data access and higher overhead.

**2. Vectorization:**

**NumPy:** Supports vectorized operations, which means that operations on entire arrays are performed using low-level, optimized code. This avoids the overhead of Python’s dynamic typing and loop execution.

**Python Lists:** Operations typically require explicit loops, which are slower due to Python’s interpretive nature and the overhead of dynamically typing and handling each element.

**Example:**

In [11]:
import numpy as np
import time

# NumPy operation
arr = np.arange(1000000)
start_time = time.time()
arr_squared = arr ** 2
print("NumPy time:", time.time() - start_time)

# Python list operation
lst = list(range(1000000))
start_time = time.time()
lst_squared = [x ** 2 for x in lst]
print("Python list time:", time.time() - start_time)

NumPy time: 0.006426095962524414
Python list time: 0.3508913516998291


In this example, the NumPy operation is likely to be significantly faster than the Python list operation due to vectorization.

**3. Broadcasting:**

**NumPy:** Allows for efficient operations on arrays of different shapes without the need for explicit looping. Broadcasting automatically adjusts the shapes of arrays for element-wise operations.

**Python Lists:** Broadcasting is not natively supported, and operations involving lists of different shapes would require manual implementation, which can be cumbersome and inefficient.

**Example:**

In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2
broadcasted_arr = arr + scalar

**4. Optimized Mathematical Functions:**

**NumPy:** Provides a wide range of optimized mathematical functions (e.g., trigonometric functions, logarithms) that are implemented in C and can be executed very efficiently.

**Python Lists:** Lack built-in support for these operations, and similar functionality would require manual implementation or use of slower methods from other libraries.

**5. Memory Efficiency:**

**NumPy:** Uses fixed-size data types (e.g., int32, float64), which are more memory-efficient than Python lists. Arrays are stored in a compact format, which reduces memory overhead.

**Python Lists:** Store elements as references to objects, which introduces additional memory overhead for each element due to metadata and dynamic typing.

**6. Parallel Processing:**

**NumPy:** Operations can be parallelized using optimized libraries like BLAS and LAPACK, which leverage multi-core processors and SIMD instructions.

**Python Lists:** Do not support parallel processing natively. Operations on lists are inherently sequential and cannot benefit from parallelism without explicit parallelization strategies.

**7. Ease of Integration with Other Libraries:**

**NumPy:** Many scientific and data analysis libraries (e.g., SciPy, pandas, TensorFlow) are built on top of NumPy arrays, ensuring efficient interoperability and consistent performance across different tools.

**Python Lists:** Integration with numerical libraries typically requires conversion to NumPy arrays, adding overhead and complexity.

#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively. These functions help in combining multiple arrays into one by aligning them along specific axes. Let’s explore their differences, usage, and outputs with examples.

**1. np.vstack():** Vertical Stacking

**Purpose:** Stacks arrays along the vertical axis (i.e., row-wise). The input arrays are stacked on top of each other.

**Requirements:** All arrays must have the same number of columns.
**Example:**

In [13]:
import numpy as np

# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack vertically
result_vstack = np.vstack((arr1, arr2))

print(result_vstack)

[[1 2 3]
 [4 5 6]]


The two 1D arrays are stacked to form a 2D array where each input array becomes a row.

**Example with 2D Arrays:**

In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])

# Vertical stacking
result_vstack_2d = np.vstack((arr1, arr2))

print(result_vstack_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In this case, arr1 and arr2 are 2D arrays, and vstack() appends arr2 as a new row beneath arr1.

**2. np.hstack():** Horizontal Stacking

**Purpose:** Stacks arrays along the horizontal axis (i.e., column-wise). The input arrays are placed side by side.

**Requirements:** All arrays must have the same number of rows.

**Example:**

In [15]:
import numpy as np

# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack horizontally
result_hstack = np.hstack((arr1, arr2))

print(result_hstack)

[1 2 3 4 5 6]


Here, the two 1D arrays are combined into a single 1D array by appending arr2 to arr1.

**Example with 2D Arrays:**

In [16]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Horizontal stacking
result_hstack_2d = np.hstack((arr1, arr2))

print(result_hstack_2d)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Here, arr1 and arr2 are stacked horizontally, forming a new array by placing the columns of arr2 to the right of arr1.

#8. Explain the differences between flipir() and flipud() methods in NurnPy, including their effects on various array dimensions.

In NumPy, the flipud() and fliplr() methods are used to reverse the order of elements in a 2D array, but they operate on different axes:

**1. np.flipud() (Flip Up-Down):**

**Functionality:** It reverses the array along the vertical axis, effectively flipping the array "upside down."

**Effect:** Rows are reversed, meaning the last row becomes the first row, and the first row becomes the last.

**Applicable on:** Any array with at least one dimension (including 1D and higher-dimensional arrays). For 1D arrays, it behaves like reversing the array.

**Example (2D array):**

In [17]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result_flipud = np.flipud(arr)
print(result_flipud)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


The rows are flipped vertically, with the top row becoming the bottom row.

**2. np.fliplr() (Flip Left-Right):**

**Functionality:** It reverses the array along the horizontal axis, flipping the array "left to right."

**Effect:** Columns are reversed, meaning the last column becomes the first, and the first column becomes the last.

**Applicable on:** Only 2D arrays or higher. For 1D arrays, it raises an error since flipping left-right doesn't apply to a 1D structure.

**Example (2D array):**

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result_fliplr = np.fliplr(arr)
print(result_fliplr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


The columns are flipped horizontally, with the leftmost column becoming the rightmost column.

#9. Discuss the functionality of the array_split() method in NumPy, How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is similar to the split() method, but it handles uneven splits more flexibly, making it very useful when the number of sections does not divide the array evenly.

**Functionality of array_split()**

**Purpose:** To split an array into a specified number of sub-arrays. Unlike split(), it can handle uneven splits by adjusting the size of the resulting sub-arrays when the array cannot be divided equally.

**Syntax:** numpy.array_split(ary, indices_or_sections, axis=0)

**Parameters:**

**1. ary:** The input array to be split.

**2. indices_or_sections:**
The number of equal or unequal sections to split the array into. This can be an integer (for equal sections) or a list of indices (for specific positions to split the array).
**3. axis:** The axis along which the split should be performed (default is 0, i.e., row-wise split for 2D arrays).

**Handling Uneven Splits:**
When the array length is not divisible evenly by the number of splits:

**array_split()** ensures that the first few sub-arrays have an extra element compared to the later sub-arrays. This approach balances the sub-array sizes as evenly as possible.

**Examples:**

**1. Even Split:**

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 equal parts
result = np.array_split(arr, 3)
for sub_arr in result:
    print(sub_arr)

[1 2]
[3 4]
[5 6]


Since the array length is evenly divisible by 3, it splits into sub-arrays of equal size.

**2. Uneven Split:**

In [20]:
arr = np.array([1, 2, 3, 4, 5])

# Split the array into 3 parts (uneven)
result = np.array_split(arr, 3)
for sub_arr in result:
    print(sub_arr)

[1 2]
[3 4]
[5]


The array length (5) is not evenly divisible by 3. Therefore, the first two sub-arrays get 2 elements each, while the last sub-array gets 1 element.

**3. Splitting Along a Specific Axis (2D Array):**

In [21]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split the 2D array into 2 parts along axis 0 (row-wise)
result = np.array_split(arr_2d, 2, axis=0)
for sub_arr in result:
    print(sub_arr)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


The 2D array is split into 2 parts along the rows (axis 0). Since there are 3 rows, the first sub-array gets 2 rows, and the second sub-array gets 1 row.

**4. Specifying Split Indices:**

You can also specify the exact indices where you want the split to occur:

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split at specified positions
result = np.array_split(arr, [2, 5])
for sub_arr in result:
    print(sub_arr)

[1 2]
[3 4 5]
[6 7]


The array is split into three sub-arrays: one ending at index 2, one ending at index 5, and the remaining elements form the last sub-array.

#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization and broadcasting are two powerful concepts in NumPy that significantly contribute to the efficiency and speed of array operations by avoiding explicit loops and enabling element-wise operations across arrays of different shapes. Let’s break them down and explain their importance in numerical computing.

**1. Vectorization in NumPy
Concept:**

Vectorization refers to the process of performing operations on entire arrays (or large chunks of data) at once, rather than iterating through individual elements in a loop. NumPy leverages this by executing operations using low-level C code, allowing it to perform computations much faster than pure Python loops.

**Without vectorization (using a Python loop):**


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Element-wise squaring using a loop
for i in arr:
    result.append(i ** 2)
print(result)

[1, 4, 9, 16, 25]


**With vectorization:**

In [24]:
result = arr ** 2
print(result)

[ 1  4  9 16 25]


**Performance benefit:**

The vectorized version is much faster because NumPy operations are implemented in optimized C code that avoids the overhead of Python loops and dynamic typing. This leads to massive speed improvements, especially for large arrays.

**Example:**

In [25]:
import numpy as np
import time

arr = np.arange(1000000)

# Using a Python loop (no vectorization)
start = time.time()
result = [x ** 2 for x in arr]
print("Loop time:", time.time() - start)

# Using NumPy vectorization
start = time.time()
result = arr ** 2
print("Vectorization time:", time.time() - start)

Loop time: 0.36453747749328613
Vectorization time: 0.01730656623840332


The vectorized version will be significantly faster.

**Key Benefits of Vectorization:**

**Speed:** Vectorized operations are highly optimized and execute much faster than looping over elements.
Simplicity: Code becomes more concise and readable.

**Memory efficiency:** By avoiding intermediate steps and loops, vectorized operations use memory more efficiently.

**2. Broadcasting in NumPy**

**Concept:**

Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes without explicitly replicating data. It automatically expands the dimensions of smaller arrays to match the dimensions of larger ones so that the operation can be performed element-wise.

**Basic idea:** When operating on arrays of different shapes, NumPy automatically broadcasts the smaller array across the larger one. This avoids the need for creating large, memory-intensive copies of arrays.

**Broadcasting Rules:**
1. If the arrays have different numbers of dimensions, the smaller array is padded with ones on its left (front).
2. If the sizes of the arrays differ along any dimension, the array with size 1 in that dimension is stretched to match the size of the larger array.
3. If sizes differ in a non-compatible way (not 1 or the same size), broadcasting fails.

**Example 1: Broadcasting a scalar**

In [26]:
import numpy as np

arr = np.array([1, 2, 3])
result = arr + 10  # Scalar is broadcast to match the shape of `arr`
print(result)

[11 12 13]


Here, the scalar 10 is broadcast to match the shape of the array [1, 2, 3], allowing element-wise addition.

**Example 2: Broadcasting a 1D array to a 2D array**

In [27]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

result = arr2d + arr1d
print(result)

[[11 22 33]
 [14 25 36]]


In this example, the 1D array arr1d with shape (3,) is broadcast across the rows of the 2D array arr2d, allowing element-wise addition without explicitly replicating the smaller array.

**Broadcasting Example with Different Shapes:**

In [28]:
arr2d = np.array([[1], [2], [3]])
arr1d = np.array([10, 20, 30])

result = arr2d + arr1d
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


Here, the 1D array arr1d is broadcast across the columns, and the 2D array arr2d is broadcast along the rows. This allows element-wise operations across arrays of different shapes.

**How Vectorization and Broadcasting Improve Efficiency:**

1. Avoiding Loops:

Both vectorization and broadcasting eliminate the need for explicit Python loops, which are slow due to Python’s dynamic typing and interpreter overhead. By relying on C-level operations, NumPy performs operations much faster.

2. Memory Efficiency:

Broadcasting allows operations on arrays of different shapes without creating unnecessary copies of arrays in memory. The smaller array is conceptually expanded to match the size of the larger array without actual duplication.

3. Parallelization:

Vectorized operations can take advantage of modern CPU architectures, which allow parallel processing and SIMD (Single Instruction Multiple Data) optimizations. This further accelerates computations.

4. Simplified Code:

Both vectorization and broadcasting make the code more concise, readable, and easier to write. Complex operations can be expressed in fewer lines of code without sacrificing performance.